#!/usr/bin/env python3
"""
Creates a Pull Request from an issue submitted via template.
Runs in the create-pr-from-issue.yml workflow.

Expected environment variables:
  GITHUB_TOKEN   - GitHub token with write permissions
  ISSUE_BODY     - Issue body (formatted by the YAML template)
  ISSUE_NUMBER   - Issue number
  LABEL_NAME     - Issue label (whitelist-request | blacklist-request | false-positive)
"""

import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

import yaml

# Mapping from labels to rule configuration
RULE_MAP = {
    "whitelist-request": {
        "file": "rules/whitelist.yaml",
        "root_key": "repositories",
    },
    "blacklist-request": {
        "file": "rules/blacklist.yaml",
        "root_key": "repositories",
    },
    "false-positive": {
        "file": "rules/false_positives.yaml",
        "root_key": "issues",
    },
}


def get_env_or_fail(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        print(f"::error::Missing required env var: {name}")
        sys.exit(1)
    return value


def parse_issue_body(body: str) -> dict:
    """Parses an issue body generated by a YAML form template.

    The format is:
    ### Field Name
    value

    ### Next Field
    value
    """
    data = {}
    current_field = None
    current_value: list[str] = []

    for line in body.splitlines():
        if line.startswith("### "):
            if current_field is not None:
                data[current_field] = "\n".join(current_value).strip()
            current_field = line.removeprefix("### ").strip()
            current_value = []
        elif current_field is not None:
            current_value.append(line)

    if current_field is not None:
        data[current_field] = "\n".join(current_value).strip()

    return data


def github_api(method: str, endpoint: str, token: str) -> dict:
    """Calls the GitHub REST API and returns parsed JSON."""
    url = f"https://api.github.com{endpoint}"
    req = urllib.request.Request(url, method=method)
    req.add_header("Authorization", f"Bearer {token}")
    req.add_header("Accept", "application/vnd.github.v3+json")
    req.add_header("User-Agent", "hacs-compatibility-auditor-rules")

    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as e:
        body = e.read().decode()
        print(f"::error::GitHub API error {e.code} for {endpoint}: {body}")
        sys.exit(1)


def repo_exists(full_name: str, token: str) -> bool:
    """Checks if a repository exists on GitHub."""
    try:
        github_api("GET", f"/repos/{full_name}", token)
        return True
    except SystemExit:
        return False


def load_yaml(filepath: Path) -> dict:
    """Loads a YAML file or returns an empty dict if it doesn't exist."""
    if not filepath.exists():
        return {}
    with open(filepath, encoding="utf-8") as f:
        data = yaml.safe_load(f)
    return data if isinstance(data, dict) else {}


def is_duplicate_entry(filepath: Path, new_entry: dict, rule_type: str) -> bool:
    """Checks if an entry already exists in the rules file."""
    data = load_yaml(filepath)
    root_key = RULE_MAP[rule_type]["root_key"]
    entries = data.get(root_key, [])

    for entry in entries:
        if rule_type == "false-positive":
            if (entry.get("full_name") == new_entry.get("full_name") and
                    entry.get("issue_number") == new_entry.get("issue_number")):
                return True
        else:
            if entry.get("full_name") == new_entry.get("full_name"):
                return True
    return False


def append_entry(filepath: Path, entry: dict, rule_type: str):
    """Appends an entry to the rules file."""
    data = load_yaml(filepath)
    root_key = RULE_MAP[rule_type]["root_key"]
    if root_key not in data:
        data[root_key] = []
    data[root_key].append(entry)

    filepath.parent.mkdir(parents=True, exist_ok=True)
    with open(filepath, "w", encoding="utf-8") as f:
        yaml.dump(data, f, sort_keys=False, allow_unicode=True, indent=2)


def main():
    token = get_env_or_fail("GITHUB_TOKEN")
    issue_body = get_env_or_fail("ISSUE_BODY")
    issue_number = get_env_or_fail("ISSUE_NUMBER")
    label_name = get_env_or_fail("LABEL_NAME")
    repo_full = os.environ.get("GITHUB_REPOSITORY", "")

    rule_cfg = RULE_MAP.get(label_name)
    if rule_cfg is None:
        print(f"::error::Unknown label: {label_name}")
        sys.exit(1)

    rule_file = Path(rule_cfg["file"])
    parsed = parse_issue_body(issue_body)
    issue_url = f"https://github.com/{repo_full}/issues/{issue_number}"

    # Extract common fields
    full_name = parsed.get("Repository", "").strip()
    if not full_name or "/" not in full_name:
        print("::error::Invalid repository format. Must be owner/repo")
        sys.exit(1)

    if not repo_exists(full_name, token):
        print(f"::error::Repository {full_name} does not exist on GitHub")
        sys.exit(1)

    reason = parsed.get("Reason", "").strip()
    if not reason:
        print("::error::Reason is required")
        sys.exit(1)

    # Build entry based on type
    if label_name in ("whitelist-request", "blacklist-request"):
        ha_version = parsed.get("Home Assistant Version", "").strip() or "*"
        entry = {
            "full_name": full_name,
            "reason": reason,
            "ha_version": ha_version,
            "added": "",
            "issue": issue_url,
        }
    else:
        issue_num_raw = parsed.get("Issue Number", "").strip()
        if not issue_num_raw:
            print("::error::Issue number is required")
            sys.exit(1)
        try:
            issue_num = int(issue_num_raw)
        except ValueError:
            print(f"::error::Invalid issue number: {issue_num_raw}")
            sys.exit(1)

        # Verify the issue exists
        try:
            github_api("GET", f"/repos/{full_name}/issues/{issue_num}", token)
        except SystemExit:
            print(f"::error::Issue #{issue_num} does not exist in {full_name}")
            sys.exit(1)

        entry = {
            "full_name": full_name,
            "issue_number": issue_num,
            "reason": reason,
            "added": "",
            "issue": issue_url,
        }

    # Check for duplicates
    if is_duplicate_entry(rule_file, entry, label_name):
        print(f"::error::Entry already exists in {rule_file}")
        sys.exit(1)

    # Append entry to rule file
    append_entry(rule_file, entry, label_name)

    # Workflow outputs
    branch = f"rules/{label_name}-{issue_number}"
    print(f"BRANCH={branch}")
    print(f"FILE={rule_cfg['file']}")

    # GitHub Actions output
    with open(os.environ.get("GITHUB_OUTPUT", "NUL"), "a" if "GITHUB_OUTPUT" in os.environ else "w") as f:
        print(f"branch={branch}", file=f)
        print(f"file={rule_cfg['file']}", file=f)

    print(f"[OK] Entry created for {full_name} in {rule_cfg['file']}")
    print(f"[OK] Branch: {branch}")


if __name__ == "__main__":
    main()
